/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CockpitPersonaRouteImport } from './routes/cockpit.$persona'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitPersonaRoute = CockpitPersonaRouteImport.update({
  id: '/cockpit/$persona',
  path: '/cockpit/$persona',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cockpit/$persona': typeof CockpitPersonaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cockpit/$persona': typeof CockpitPersonaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cockpit/$persona': typeof CockpitPersonaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cockpit/$persona'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cockpit/$persona'
  id: '__root__' | '/' | '/cockpit/$persona'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CockpitPersonaRoute: typeof CockpitPersonaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/$persona': {
      id: '/cockpit/$persona'
      path: '/cockpit/$persona'
      fullPath: '/cockpit/$persona'
      preLoaderRoute: typeof CockpitPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CockpitPersonaRoute: CockpitPersonaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
